---
apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: sub-inv-ui-test
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: ClowdJobInvocation
    metadata:
      name: sub-inv-ui-test-${IMAGE_TAG}-${UID}
      annotations:
        'ignore-check.kube-linter.io/no-liveness-probe': 'probes not required on Job pods'
        'ignore-check.kube-linter.io/no-readiness-probe': 'probes not required on Job pods'
    spec:
      appName: rhsm-api-proxy
      testing:
        iqePlugin: subscription_central
        iqe:
          debug: false
          dynaconfEnvName: stage
          marker: 'subscriptions'
          plugins: subscription_central
          ui:
            selenium:
              deploy: true
parameters:
  - name: IMAGE_TAG
    value: ''
    required: true
  - name: UID
    description: 'Unique CJI name suffix'
    generate: expression
    from: '[a-z0-9]{6}'
